// Regenerates src/daily/words.ts.
//
// Why: ALLOWED_GUESSES was a tiny (~770-word) curated list, so common valid words
// (HUMAN, MONTH, ABOUT, ...) were rejected with NOT_IN_WORD_LIST — the game became
// unplayable. Standard Wordle design: a small curated ANSWERS pool (kept as-is, so
// daily answers stay fair) + a large ALLOWED_GUESSES dictionary for what players may
// type. We union the comprehensive english-words 5-letter set with the existing
// curated lists, so nothing previously accepted regresses — we only ADD acceptance.
//
// Run: pnpm --filter @wordlelo/be build && node tools/gen-words.mjs
// (src/daily/words.ts is biome-ignored as generated output.)
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import english from "an-array-of-english-words" with { type: "json" };
// Read the *current* curated lists from the built module so ANSWERS is preserved
// byte-for-byte (changing it would change the daily answers / on-chain commitments).
import { ALLOWED_GUESSES, ANSWERS } from "../dist/daily/words.js";

const here = dirname(fileURLToPath(import.meta.url));

const guessSet = new Set();
for (const w of english) {
  if (/^[a-z]{5}$/.test(w)) guessSet.add(w.toUpperCase());
}
// Union with the existing curated lists → strict superset, zero regression.
for (const w of ALLOWED_GUESSES) guessSet.add(w);
for (const w of ANSWERS) guessSet.add(w);

const guesses = [...guessSet].sort();
const answers = [...ANSWERS].sort();

// Invariant: every answer MUST be an accepted guess.
const gset = new Set(guesses);
const missing = answers.filter((a) => !gset.has(a));
if (missing.length) throw new Error(`answers not in guesses: ${missing.join(", ")}`);

const header =
  "// AUTO-GENERATED by tools/gen-words.mjs — do not edit by hand.\n" +
  "// ALLOWED_GUESSES: full 5-letter English dictionary (an-array-of-english-words)\n" +
  "// unioned with the curated lists, so accepted guesses only grow, never shrink.\n" +
  "// ANSWERS: curated daily-answer pool (unchanged — drives on-chain commitments).\n";

const answerLines = answers.map((w) => `  "${w}",`).join("\n");
const file = `${header}
// Packed as a space-joined string (split at load) to keep this file compact.
export const ALLOWED_GUESSES: readonly string[] = "${guesses.join(" ")}".split(" ");

export const ANSWERS: readonly string[] = [
${answerLines}
];

export const ALLOWED_SET: ReadonlySet<string> = new Set(ALLOWED_GUESSES);
`;

writeFileSync(join(here, "../src/daily/words.ts"), file);
console.log(
  `wrote words.ts — guesses=${guesses.length} answers=${answers.length} ` +
    `HUMAN=${gset.has("HUMAN")} MONTH=${gset.has("MONTH")} ABOUT=${gset.has("ABOUT")}`,
);
